### ISSUE TITLE
Database Update

### ISSUE THREAD

**Issue by danilcolak** [menkhus/falco#11]
Whenever I try to update the database it returns "broken pipe" error and deletes installed XML's which contains cve information year by year.
Note: The main problem is at load.sh nvd2sqlite(command not found).I installed all the dependencies to the working platform.

**Comment by menkhus** [comment]
I need to update the app published on github for the current logic I have, which uses the JSON from NIST NVD feed.  Sorry I left an app with outdated dependencies.

Closing this issue. 

Next falco version will have code to work with latest JSON and uses mysql in the back end.
